### ISSUE TITLE
Missing methods from the interface

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/AbstractPermutations.jl#7]
- [x] `isless` - the lexicographical ordering #18 
- [x] other orders (e.g. `deglex` via defining `DegLex <: Base.Order.Ordering` + `lt(DegLex(), p, q)` #18 
- [x] `Base.:(^)(p::Permutation, i::Integer)`. (e.g. for small (in absvalue) `i`s use `i^p^p^p^p` for larger compute cycle decomposition and shift). #17
